### ISSUE TITLE
Fix Kyma issues

### ISSUE THREAD

**Issue by madronalabs** [madronalabs/soundplane#26]
There is at least one major connection bug preventing a user from using the latest version.
Testing and development with Kyma here would be helpful.

**Comment by ngwese** [comment]
If there are more details on this bug I could probably help find and fix it (as I have everything needed to do development and testing).

**Comment by madronalabs** [comment]
Great, thanks for the note. I know there is at least one connection issue forcing a user to stay on an older version. I’ll be working on it very soon.

**Comment by madronalabs** [comment]
Attempted a fix. No Kyma here for testing unfortunately!

**Comment by madronalabs** [comment]
Fixed, according to a Kyma user.
